# <center>Ćwiczenie 2 -TIER protocol i tidy data</center>

**Marcin Brzózka  
nr albumu 405499  
grupa 2**

Najpierw ustalam numer mojego datasetu:  
**N = 7  
Numer datasetu = (7 mod 5) + 1 = 3**
Wybranym datasetem jest billboard.csv - notowania billboardu.

In [1]:
# Zaimportowanie wymaganych bibliotek.
import numpy as np
import pandas as pd
import os

**Wczytanie pliku csv z danymi**

In [2]:
data = pd.read_csv(r'../original_data/billboard.csv', encoding= 'unicode_escape')
data

,year,artist.inverted,track,time,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
0,2000,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,78,63.0,49.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,Santana,"Maria, Maria",4:18,Rock,2000-02-12,2000-04-08,15,8.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,Savage Garden,I Knew I Loved You,4:07,Rock,1999-10-23,2000-01-29,71,48.0,43.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,Madonna,Music,3:45,Rock,2000-08-12,2000-09-16,41,23.0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,Rock,2000-08-05,2000-10-14,57,47.0,45.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,2000,Ghostface Killah,Cherchez LaGhost,3:04,R&B,2000-08-05,2000-08-05,98,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,2000,"Smith, Will",Freakin' It,3:58,Rap,2000-02-12,2000-02-12,99,99.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,2000,Zombie Nation,Kernkraft 400,3:30,Rock,2000-09-02,2000-09-02,99,99.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,2000,"Eastsidaz, The",Got Beef,3:58,Rap,2000-07-01,2000-07-01,99,99.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,2000,Fragma,Toca's Miracle,3:22,R&B,2000-10-28,2000-10-28,99,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**Stworzenie tabeli w nowej formie na dane**  
Pominięcie danej z rokiem

In [3]:
better_data = pd.DataFrame({
    'artist': [data.values[0][1]], 'track': [data.values[0][2]],
    'time': [data.values[0][3]], 'genre': [data.values[0][4]],
    'date entered': [data.values[0][5]], 'date peaked': [data.values[0][6]],
    'week': int(1), 'rank': int(data.values[0][7])
})

**Uzupełnienie nowej tabeli**

In [4]:
X, Y = data.shape
for i in range(X):
    for j in range(7, Y):
        if not np.isnan(data.iloc[i][j]) and (i != 0 or j != 7):
            X_1 = better_data.shape[0]
            better_data.loc[X_1, :] = [data.values[i][1], data.values[i][2], data.values[i][3], data.values[i][4],
                data.values[i][5], data.values[i][6], int(j-6), data.iloc[i][j]]
better_data

,artist,track,time,genre,date entered,date peaked,week,rank
0,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,1.0,78.0
1,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,2.0,63.0
2,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,3.0,49.0
3,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,4.0,33.0
4,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,5.0,23.0
...,...,...,...,...,...,...,...,...
5302,Zombie Nation,Kernkraft 400,3:30,Rock,2000-09-02,2000-09-02,1.0,99.0
5303,Zombie Nation,Kernkraft 400,3:30,Rock,2000-09-02,2000-09-02,2.0,99.0
5304,"Eastsidaz, The",Got Beef,3:58,Rap,2000-07-01,2000-07-01,1.0,99.0
5305,"Eastsidaz, The",Got Beef,3:58,Rap,2000-07-01,2000-07-01,2.0,99.0
5306,Fragma,Toca's Miracle,3:22,R&B,2000-10-28,2000-10-28,1.0,99.0

**Eksport danych do pliku z rozszerzeniem csv oraz xlsx**

In [5]:
better_data.to_csv(r"../analysis_data/billboard_v2.csv", encoding= 'unicode_escape')
better_data.to_excel(r"../analysis_data/billboard_v2.xlsx", encoding= 'unicode_escape', index=False)